# 网站基本信息
title: Fluid Resonance
description: tracing the inner voice, word by word.
author: Tao Zhang

# 使用 Minima 主题
theme: minima

# Minima 主题设置
minima:
    date_format: "%Y-%m-%d" # 日期格式

# 社交媒体链接（可选）
social_links:
    github: rhythmfromwithin

# 其他设置
show_excerpts: true # 在首页显示文章摘要

# 支持中文和UTF-8字符
encoding: utf-8
timezone: Asia/Shanghai

# 设置集合 - 只添加您现有的一两个文件夹作为测试
collections:
    6_把话说给宇宙听--致敬那些无以名状的存在: # 替换为您实际的文件夹名
        output: true
        permalink: /:collection/:name/

# 为测试的集合设置默认布局
defaults:
    - scope:
          path: ""
          type: "6_把话说给宇宙听--致敬那些无以名状的存在" # 替换为您实际的文件夹名
      values:
          layout: post
